routes/web.php
<?php

Auth::routes();

Route::get('/', 'PostController@index')->name('home');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');

Route::get('/', ['as' => 'index', 'uses' => 'HomeController@getIndex']);
Route::group(['middleware' => 'guest'], function() {
    Route::get('/login', ['as' => 'login', 'uses' => 'HomeController@getLoginPage']);
    Route::post('/login', ['as' => 'attempt_login', 'uses' => 'HomeController@attemptLogin']);
});


Route::group(['middleware' => 'auth'], function() {
    Route::get('/logout', ['as' => 'logout', 'uses' => 'HomeController@logout']);
    Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@getDashboard']);
    //Unit
    Route::group(['prefix' => 'unit', 'middleware' => 'mainUnit'], function() {
        Route::get('/list-unit', ['as' => 'list_unit', 'uses' => 'UnitController@listUnit']);
        Route::get('/add-unit', ['as' => 'add_unit', 'uses' => 'UnitController@addUnit']);
        Route::post('/save-unit', ['as' => 'save_unit', 'uses' => 'UnitController@saveUnit']);
        Route::get('/view-unit/{id}', ['as' => 'view_unit', 'uses' => 'UnitController@viewUnit']);
        Route::get('/edit-unit/{id}', ['as' => 'edit_unit', 'uses' => 'UnitController@editUnit']);
        Route::post('/update-unit/{id}', ['as' => 'update_unit', 'uses' => 'UnitController@updateUnit']);
        Route::get('/unpublish-unit/{id}', ['as' => 'unpublish_unit', 'uses' => 'UnitController@unpublishUnit']);
        Route::get('/publish-unit/{id}', ['as' => 'publish_unit', 'uses' => 'UnitController@publishUnit']);
        Route::get('/delete-unit/{id}', ['as' => 'delete_unit', 'uses' => 'UnitController@deleteUnit']);
    });
    //Employee
    Route::group(['prefix' => 'employee'], function() {
        //Employee
        Route::get('/list-employee', ['as' => 'list_employee', 'uses' => 'EmployeeController@listEmployee']);
        Route::get('/add-employee', ['as' => 'add_employee', 'uses' => 'EmployeeController@addEmployee']);
        Route::post('/save-employee', ['as' => 'save_employee', 'uses' => 'EmployeeController@saveEmployee']);
        Route::get('/view-employee/{id}', ['as' => 'view_employee', 'uses' => 'EmployeeController@viewEmployee']);
        Route::get('/edit-employee/{id}', ['as' => 'edit_employee', 'uses' => 'EmployeeController@editEmployee']);
        Route::post('/update-employee/{id}', ['as' => 'update_employee', 'uses' => 'EmployeeController@updateEmployee']);
        Route::get('/unpublish-employee/{id}', ['as' => 'unpublish_employee', 'uses' => 'EmployeeController@unpublishEmployee']);
        Route::get('/publish-employee/{id}', ['as' => 'publish_employee', 'uses' => 'EmployeeController@publishEmployee']);
        Route::get('/delete-employee/{id}', ['as' => 'delete_employee', 'uses' => 'EmployeeController@deleteEmployee']);
    });
    
    //News
    Route::group(['prefix' => 'news'], function() {
        Route::get('/list-news', ['as' => 'list_news', 'uses' => 'NewsController@listNews']);
        Route::post('/save-news', ['as' => 'save_news', 'uses' => 'NewsController@saveNews']);
        Route::get('/view-news/{id}', ['as' => 'view_news', 'uses' => 'NewsController@viewNews']);
        Route::get('/edit-news/{id}', ['as' => 'edit_news', 'uses' => 'NewsController@editNews']);
        Route::post('/update-news/{id}', ['as' => 'update_news', 'uses' => 'NewsController@updateNews']);
        Route::get('/unpublish-news/{id}', ['as' => 'unpublish_news', 'uses' => 'NewsController@unpublishNews']);
        Route::get('/publish-news/{id}', ['as' => 'publish_news', 'uses' => 'NewsController@publishNews']);
        Route::get('/delete-news/{id}', ['as' => 'delete_news', 'uses' => 'NewsController@deleteNews']);
    });
    
    //Announcement
    Route::group(['prefix' => 'announcement'], function() {
        Route::get('/list-announcement', ['as' => 'list_announcement', 'uses' => 'AnnouncementController@listAnnouncement']);
        Route::get('/add-announcement', ['as' => 'add_announcement', 'uses' => 'AnnouncementController@addAnnouncement']);
        Route::post('/save-announcement', ['as' => 'save_announcement', 'uses' => 'AnnouncementController@saveAnnouncement']);
        Route::get('/view-announcement/{id}', ['as' => 'view_announcement', 'uses' => 'AnnouncementController@viewAnnouncement']);
        Route::get('/edit-announcement/{id}', ['as' => 'edit_announcement', 'uses' => 'AnnouncementController@editAnnouncement']);
        Route::post('/update-announcement/{id}', ['as' => 'update_announcement', 'uses' => 'AnnouncementController@updateAnnouncement']);
        Route::get('/unpublish-announcement/{id}', ['as' => 'unpublish_announcement', 'uses' => 'AnnouncementController@unpublishAnnouncement']);
        Route::get('/publish-announcement/{id}', ['as' => 'publish_announcement', 'uses' => 'AnnouncementController@publishAnnouncement']);
        Route::get('/delete-announcement/{id}', ['as' => 'delete_announcement', 'uses' => 'AnnouncementController@deleteAnnouncement']);
    });
    
    //Status
    Route::group(['prefix' => 'status'], function() {
        Route::get('/list-status', ['as' => 'list_status', 'uses' => 'StatusController@listStatus']);
        Route::get('/add-status', ['as' => 'add_status', 'uses' => 'StatusController@addStatus']);
        Route::post('/save-status', ['as' => 'save_status', 'uses' => 'StatusController@saveStatus']);
        Route::get('/view-status/{id}', ['as' => 'view_status', 'uses' => 'StatusController@viewStatus']);
        Route::get('/edit-status/{id}', ['as' => 'edit_status', 'uses' => 'StatusController@editStatus']);
        Route::post('/update-status/{id}', ['as' => 'update_status', 'uses' => 'StatusController@updateStatus']);
        Route::get('/unpublish-status/{id}', ['as' => 'unpublish_status', 'uses' => 'StatusController@unpublishStatus']);
        Route::get('/publish-status/{id}', ['as' => 'publish_status', 'uses' => 'StatusController@publishStatus']);
        Route::get('/delete-status/{id}', ['as' => 'delete_status', 'uses' => 'StatusController@deleteStatus']);
    });
    
    //Message
    Route::group(['prefix' => 'message'], function() {
        Route::get('/compose', ['as' => 'compose_message', 'uses' => 'MessageController@composeMessage']);
        Route::post('/send', ['as' => 'send_message', 'uses' => 'MessageController@sendMessage']);
        Route::get('/inbox', ['as' => 'inbox_message', 'uses' => 'MessageController@inboxMessage']);
        Route::get('inbox/{id}/view', ['as' => 'view_inbox', 'uses' => 'MessageController@viewInbox']);
        Route::get('/sent', ['as' => 'sent_message', 'uses' => 'MessageController@sentMessage']);
        Route::get('sent/{id}/view', ['as' => 'view_sent', 'uses' => 'MessageController@viewSent']);
        Route::get('/edit-message/{id}', ['as' => 'edit_message', 'uses' => 'MessageController@editMessage']);
        Route::post('/update-message/{id}', ['as' => 'update_message', 'uses' => 'MessageController@updateMessage']);
        Route::get('/unpublish-message/{id}', ['as' => 'unpublish_message', 'uses' => 'MessageController@unpublishMessage']);
        Route::get('/publish-message/{id}', ['as' => 'publish_message', 'uses' => 'MessageController@publishMessage']);
        Route::get('/delete-message/{id}', ['as' => 'delete_message', 'uses' => 'MessageController@deleteMessage']);
    });
});

resources/views/partials/control_sidebar.blade.php
<!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

resources/views/partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <strong>Powered by <a href="http://shadowhiteanimators.com">Shadowhite Animators Ltd.</a></strong>
    </div>
    <span>Version: <a href="http://shadowhiteanimators.com">1.1</a></span> 
    <span class="hidden">Developed by <a href="http://shadowhiteanimators.com">Md. Arif Khan</a></span> 
</footer>

resources/views/partials/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{route('index')}}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>D</b>R</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Daily</b>Report</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li><a>{{Auth::user()->unit_name()}}</a></li>
                <!-- Notifications: style can be found in dropdown.less -->
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        @if(Auth::user()->notification_count())<span class="label label-warning">{{Auth::user()->notification_count()}}</span>@endif
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have {{Auth::user()->notification_count()}} new notifications</li>
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul class="menu">
                                @foreach(Auth::user()->notifications() as $notification)
                                <li>
                                    @if($notification->type == 'announcement')
                                    <a href="{{route('view_announcement', ['id' => $notification->target_id])}}" class="{{$notification->seen_by ? '':'text-bold'}}">
                                        <i class="fa fa-bullhorn text-aqua"></i> 
                                        1 new announcement from {{$notification->from_unit()->unit_name}}
                                    </a>
                                    @elseif($notification->type == 'status')
                                    <a href="{{route('view_status', ['id' => $notification->target_id])}}" class="{{$notification->seen_by ? '':'text-bold'}}">
                                        <i class="fa fa-check text-aqua"></i> 
                                                1 new status from {{$notification->from_unit()->unit_name}}
                                    </a>
                                    @endif
                                </li>
                                @endforeach
                                
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                <!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        @if(Auth::user()->unread_message())
                        <span class="label label-success">{{Auth::user()->unread_message()}}</span>
                        @endif
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have {{Auth::user()->unread_message()}} unread messages</li>
                        <li>
                            <!-- inner menu: contains the actual data -->
                            <ul class="menu">
                                @foreach(Auth::user()->unread_messages() as $message)
                                <li><!-- start message -->
                                    <a href="{{route('view_inbox', ['id' => $message->id])}}">
                                        <div class="pull-left">
                                            <i class="fa fa-envelope-o fa-2x"></i>
                                        </div>
                                        <h4 class="{{$message->seen_by ? '':'text-bold'}}">
                                            {{$message->from_unit()}}
                                            <small><i class="fa fa-clock-o"></i> {{$message->humanTiming()}}</small>
                                        </h4>
                                        <p>{{$message->subject}}</p>
                                    </a>
                                </li>
                                <!-- end message -->
                                @endforeach
                            </ul>
                        </li>
                        <li class="footer"><a href="{{route('inbox_message')}}">See All Messages</a></li>
                    </ul>
                </li>
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="{{route('logout')}}">
                        <span class="hidden-xs"><i class="fa fa-sign-out"></i> Sign out [{{Auth::user()->name}}]</span>
                    </a>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/partials/messages.blade.php
<div class="flash-message" >
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
    @if(Session::has('alert-' . $msg))

    <p class="alert alert-{{ $msg }}">{{ Session::pull('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
    @endif
    @endforeach
</div>

@if(count($errors) > 0)
<div class="alert alert-error">
    <button class="close" data-dismiss="alert">×</button>
    @foreach($errors->all() as $error)
    <p>
        <strong>Error!</strong>  {{ $error }}
    </p>
    @endforeach
</div>
@endif

resources/views/partials/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <img src="{{asset('public/asset/img/logo.png')}}" class="img-circle img-responsive" alt="User Image">
        </div>
        <!--      <div class="user-panel">
                <div class="pull-left image">
                  <img src="{{asset('public/health/img/mak.jpg')}}" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>{{Auth::user()->name}}</p>
                  <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
              </div>-->

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            <li class="{!! Request::is('dashboard') ? 'active' : '' !!}">
                <a href="{{route('dashboard')}}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>

            @if(Auth::user()->unit_type() == 'Main Unit')
            <li class="{!! Request::is('unit/*') ? 'active' : '' !!}">
                <a href="{{route('list_unit')}}">
                    <i class="fa fa-tree"></i> <span>Units</span>
                </a>
            </li>
            @endif
            <li class="{!! Request::is('employee/*') ? 'active' : '' !!}">
                <a href="{{route('list_employee')}}">
                    <i class="fa fa-id-card"></i> <span>Employees</span>
                </a>
            </li>
            <li class="{!! Request::is('announcement/*') ? 'active' : '' !!}">
                <a href="{{route('list_announcement')}}">
                    <i class="fa fa-bullhorn"></i> <span>Announcement</span>
                </a>
            </li>
            <li class="{!! Request::is('status/*') ? 'active' : '' !!}">
                <a href="{{route('list_status')}}">
                    <i class="fa fa-check"></i> <span>Status</span>
                </a>
            </li>
            <li class="{!! Request::is('news/*') ? 'active' : '' !!}">
                <a href="{{route('list_news')}}">
                    <i class="fa fa-newspaper-o"></i> <span>News</span>
                </a>
            </li>
            <li class="treeview {!! Request::is('message/*') ? 'active' : '' !!}">
                <a href="#">
                    <i class="fa fa-envelope"></i> <span>Message</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{!! Request::is('message/inbox') ? 'active' : '' !!}">
                        <a href="{{route('inbox_message')}}">
                            <i class="fa fa-inbox"></i> 
                            <span>Inbox 
                                @if(Auth::user()->unread_message())
                                <span class="label label-primary pull-right">{{Auth::user()->unread_message()}}</span>
                                @endif  
                            </span>
                        </a>
                    </li>
                    <li class="{!! Request::is('message/sent') ? 'active' : '' !!}">
                        <a href="{{route('sent_message')}}">
                            <i class="fa fa-envelope-o"></i> <span>Sent</span>
                        </a>
                    </li>
                    <li class="{!! Request::is('message/compose') ? 'active' : '' !!}">
                        <a href="{{route('compose_message')}}">
                            <i class="fa fa-pencil"></i> <span>Compose</span>
                        </a>
                    </li>
                </ul>
            </li>
            @role('Admin')
            <li class="header">Users, Roles & Permissions</li>

            <li class="{!! Request::is('users','users/*') ? 'active' : '' !!}">
                <a href="{{route('users.index')}}"><i class="fa fa-users"></i> Users</a>
            </li>
            <li class="{!! Request::is('roles','roles/*') ? 'active' : '' !!}">
                <a href="{{route('roles.index')}}"><i class="fa fa-bell"></i> Roles</a>
            </li>
            <li class="{!! Request::is('permissions','permissions/*') ? 'active' : '' !!}">
                <a href="{{route('permissions.index')}}"><i class="fa fa-lock"></i> Permissions</a>
            </li>
            @endrole

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>